version: '3'

services:
  broker:
    image: rabbitmq:3-management-alpine
    container_name: csgo_broker
    restart: always
    volumes:
      - ./data/rabbitmq/data/:/var/lib/rabbitmq/
    ports:
      - 127.0.0.1:5672:5672
      - 127.0.0.1:15672:15672
